version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
    time: "07:00"
  ignore:
  - dependency-name: "@types/node"
    update-types: ["version-update:semver-major"]
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "07:00"
