name: configure-credentials
description: GitHub action for configuring emulator.wtf credentials using a GitHub OIDC token
inputs:
  oidc-configuration-id:
    description: OIDC configuration ID from the emulator.wtf web app
    required: true
branding:
  color: orange
  icon: smartphone
runs:
  using: composite
  steps:
    - uses: emulator-wtf/actions/configure-credentials@42753a2a6bda2e657741a7385131bf61db464899  # v1.0.0
      with:
        oidc-configuration-id: ${{ inputs.oidc-configuration-id }}
