name: configure-credentials
description: GitHub action for configuring emulator.wtf credentials using a GitHub OIDC token
inputs:
  oidc-configuration-id:
    description: OIDC configuration ID from the emulator.wtf web app
    required: true
branding:
  color: orange
  icon: smartphone
runs:
  using: composite
  steps:
    - uses: emulator-wtf/actions/configure-credentials@8ebd78518fdcffab32d868226ec882f1be6dcb50 # v1.2.1
      with:
        oidc-configuration-id: ${{ inputs.oidc-configuration-id }}
