name: configure-credentials
description: GitHub action for configuring emulator.wtf credentials using a GitHub OIDC token
inputs:
  oidc-configuration-id:
    description: OIDC configuration ID from the emulator.wtf web app
    required: true
branding:
  color: orange
  icon: smartphone
runs:
  using: composite
  steps:
    - uses: emulator-wtf/actions/configure-credentials@72f86422814fad7432a286a1b29699cc9e73d561  # v1.1.0
      with:
        oidc-configuration-id: ${{ inputs.oidc-configuration-id }}
