name: Test
permissions:
  contents: read
  id-token: write
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: jdx/mise-action@v3
    - run: mise dist
    - uses: ./
      with:
        oidc-configuration-id: '414eac8b-5d17-4860-915f-37329ceb1dff'
    - uses: emulator-wtf/setup-ew-cli@v0
    - run: ew-cli --models
